#!/usr/bin/env bash

buildImage() {
    local registry=$1
    local imageName=$2
    local version=$3
    local options=$4
    docker build  ${options} -t ${registry}/${imageName}:${version} docker/${imageName} || { >&2 echo "Failed to build image ${imageName}"; return 1; }
}

build() {
    [[ $# -ge 2 ]] || { >&2 echo "Usage: $0 REGISTRY VERSION"; return 1; }
    local registry=$1
    local version=$2
    [[ "$3" == "localConfig" ]] || local pull="--pull"
    cp -r puppet_modules docker/idporten-bekreft-kontaktinfo/ || return 1
    cp -r puppet_hiera docker/idporten-bekreft-kontaktinfo/ || return 1
    echo Skal kopiere til jar
    cp idporten-bekreft-kontaktinfo-web/target/idporten-bekreft-kontaktinfo-web.jar docker/idporten-bekreft-kontaktinfo/jar/idporten-bekreft-kontaktinfo-web.jar || return 1
    buildImage ${registry} idporten-bekreft-kontaktinfo ${version} "${pull}" || return 1

    # codeceptjs
    rm -rf docker/codeceptjs-with-tests/tests
    cp -r codecept-tests/ docker/codeceptjs-with-tests/tests
    buildImage ${registry} codeceptjs-with-tests ${version} "${pull}" || return 1

}

build "${@}" || exit 1
